spring:
  application:
    name: hub-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  config:
    import:
      - "optional:configserver:"  # optional 추가