spring:
  datasource:
    password: ${DB_PASSWORD}

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.fhsh.daitda: DEBUG

naver:
  map:
    client-id: ${NAVER_MAP_CLIENT_ID:}
    client-secret: ${NAVER_MAP_CLIENT_SECRET:}